### ISSUE TITLE
Adding a backslash before <lang> in the paths for localization and documentation files

### ISSUE THREAD

**Issue by MeisamAmini** [nvdaaddons/AddonTemplate#18] opened 2020-12-23 18:20 UTC
Right now there isn't a backslash before the <lang> placeholder to show that the language code needs to be a folder. So the user may write, for instance, addon\localees\LC_MESSAGES\nvda.po instead of addon\locale\es\LC_MESSAGES\nvda.po. I actually did that mistake, although I had my doubts.

**Comment by josephsl** [comment] 2020-12-23 18:49
Hi, I see. Note that some of us use Linux tools to build add-ons, and add-on template is an optional package. We need a traceback if a problem with missing backslashes can be reproduced consistently. Thanks.

**Comment by MeisamAmini** [comment] 2020-12-23 22:09
No error is generated but when you install the add-on the languages you
have localized it for them don't work.

**Comment by MeisamAmini** [comment] 2020-12-23 22:11
By the way, I'm talking about the readme file. The template itself has no
problem.

**Comment by josephsl** [comment] 2020-12-23 23:21
Hi, I see multiple possibilities: the add-on in question didn’t call the addonHandler.initTranslation function (required to get the translations to show up and work), file encoding error when converting .po to .mo, among other things. Thanks.

**Comment by josephsl** [comment] 2020-12-23 23:22
Hi, ah, that clarifies a lot. I’ll look into it, as it could be the workflow issue. Thanks.

**Comment by josephsl** [comment] 2024-01-01 15:18
Hi,

January 2024 update: any updates? If not, since we haven't heard from the original poster in over three years, I vote to closing this issue.

Thanks.

**Comment by josephsl** [comment] 2024-11-14 11:15
Hi,

November 2024 update: closing as no update for over four years.

**Closed by josephsl** 2024-11-14 11:15 UTC
